version: '3.9'
services:
  qdrant:
    image: qdrant/qdrant:v1.11.7
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
